function FilterCalculator

font_size = 10;

button_size = [0.4 , 0.075];
button_x = 0.55 ;%(1-button_size(1))/2;
button_y = button_x-button_size(2);

screensize = get(0,'Screensize');
windowWidth = screensize(3)/3*2;
windowHeight = screensize(4)/2;
windowPosition = [0,0,windowWidth,windowHeight];

main_window = figure(...
    'Visible','off',...
    'Resize','off',...
    'NumberTitle','off',...
    'color','white',...
    'Name','Filter Calculator',...
    'Position',windowPosition);
movegui(main_window,'center');

%% Panels
button_group = uibuttongroup('BackgroundColor','white',...
    'Position',[0 0 0.5 1]);
right_panel = uipanel('BackgroundColor','white',...
    'Position',[0.5 0 .5 1]);

%% Left Panel Items

hText= uicontrol(button_group,...
    'Style','text',...
    'String','Filter Type',...
    'BackgroundColor','white',...
    'FontSize',font_size,...
    'Units','normalized',...
    'Position',[0,0.7,0.5,0.1]);

hPass = uicontrol(button_group,...
    'Style','popupmenu',...
    'String',{'Low-Pass','Low-Pass','Band-Pass','Band-Stop'},...
    'FontName','Copperplate Gothic Light',...
    'BackgroundColor','white',...
    'FontSize',font_size,...
    'Units','normalized',...
    'Position',[0.4,0.7,0.5,0.1],...
    'Callback',{@popup_menu_Callback});

hType = uicontrol(button_group,...
    'Style','popupmenu',...
    'String',{'Bassel','Butterworth','Tchebyschev'},...
    'FontName','Copperplate Gothic Light',...
    'BackgroundColor','white',...
    'FontSize',font_size,...
    'Units','normalized',...
    'Position',[0.4,0.6,0.5,0.1],...
    'Callback',{@popup_menu_Callback});

r2 = uicontrol(button_group,...
    'Style','radiobutton',...
    'Units','normalized',...
    'BackgroundColor','white',...
    'String','  2 dB',...
    'Position',[0.4 0.5 0.2 0.1]);

r3 = uicontrol(button_group,...
    'Style','radiobutton',...
    'Units','normalized',...
    'BackgroundColor','white',...
    'String','  3 dB',...
    'Position',[0.6 0.5 0.2 0.1]);

r5 = uicontrol(button_group,...
    'Style','radiobutton',...
    'Units','normalized',...
    'BackgroundColor','white',...
    'String',' 5 dB',...
    'Position',[0.8 0.5 0.2 0.1]);

set(button_group,'SelectedObject',r2);

hclick = uicontrol(button_group,...         % 'Click' button
    'Style','pushbutton',...
    'String','Calculate',...
    'FontName','Copperplate Gothic Light',...
    'FontSize',font_size,...
    'Units','Normalized',...
    'Position',[0.3,0.1,button_size],...
    'Callback',{@stimulusbutton_Callback});

%% Right Panel Items

haxes = axes(right_panel,...
    'Units','normalized',...
    'FontName','Copperplate Gothic Light',...
    'XLim',[0 10],...
    'YLim',[0 1],...
    'XGrid','on',...
    'XTick', 0:10,...
    'YTick', 0:0.2: 1,...
    'Position',[0.1,0.2,0.8,0.6]);
%%
pause(0.5);
set(main_window,'Visible','on');

%% Callback
    function popup_menu_Callback(src,val)
    end

    function stimulusbutton_Callback(source,~)
        
        str = get(source,'String');
        val = str2double(str);

    end

end

